name: kob-web

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - name: Pull Repository
        uses: actions/checkout@v6

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build (${{ matrix.build_type }})
        run: |
          if [ "${{ matrix.build_type }}" = "release" ]; then
            cargo build --verbose --release
          elif [ "${{ matrix.build_type }}" = "debug" ]; then
            cargo build --verbose
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: kob-web-${{ matrix.build_type }}
          path: target/${{ matrix.build_type }}/kob-web
